import os
root = os.path.dirname(workflow.snakefile)

rule hic_fastk:
    input:
        f"{root}/{config['input']['hic'].split()[0]}",
        f"{root}/{config['input']['hic'].split()[1]}"
    output:
        f"{root}/run_fastk.done"
    log:
        f"{root}/run_fastk.log"
    threads: config["fastk"]["threads"]
    resources:
        mem_gb = config["fastk"]["mem_gb"],
        time_h = config["fastk"]["time_h"]
    shell:
        f"""
        (cd {root} && ./run_fastk.sh && touch {{output}})
        """

rule hic_genescope:
    input:
        rules.hic_fastk.output
    output:
        f"{root}/run_genescope.done"
    log:
        f"{root}/run_genescope.log"
    threads: config["genescope"]["threads"]
    resources:
        mem_gb = config["genescope"]["mem_gb"],
        time_h = config["genescope"]["time_h"]
    shell:
        f"""
        (cd {root} && ./run_genescope.sh && touch {{output}})
        """

localrules: hic_all
rule hic_all:
    input:
        rules.hic_genescope.output
    output:
        f"{root}/done"
    shell:
        f"""
        (cd {root} && touch {{output}})
        """
